"""empty message

Revision ID: 3e1ddfba74a8
Revises: 73fd7ba8b925
Create Date: 2020-04-08 19:53:40.937525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1ddfba74a8'
down_revision = '73fd7ba8b925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'venue_name')
    op.drop_column('show', 'artist_image_link')
    op.drop_column('show', 'artist_name')
    op.alter_column('artist', 'id', autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('artist_image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('venue_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
