"""empty message

Revision ID: 4d1bd6f5d5c3
Revises: 3e1ddfba74a8
Create Date: 2020-04-08 21:07:43.914642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1bd6f5d5c3'
down_revision = '3e1ddfba74a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'id')
    # ### end Alembic commands ###
