"""empty message

Revision ID: 73fd7ba8b925
Revises: 888c878214dd
Create Date: 2020-04-08 19:44:35.181423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73fd7ba8b925'
down_revision = '888c878214dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_image_link', sa.String(length=500), nullable=True))
    op.add_column('show', sa.Column('artist_name', sa.String(length=120), nullable=True))
    op.add_column('show', sa.Column('venue_name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'venue_name')
    op.drop_column('show', 'artist_name')
    op.drop_column('show', 'artist_image_link')
    # ### end Alembic commands ###
