"""empty message

Revision ID: 7cd49552ae02
Revises: a9eaa1a5facd
Create Date: 2020-04-08 19:40:15.682178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7cd49552ae02'
down_revision = 'a9eaa1a5facd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start__time', sa.String(length=120), nullable=False))
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('show', 'start__time')
    # ### end Alembic commands ###
