"""empty message

Revision ID: 888c878214dd
Revises: 7cd49552ae02
Create Date: 2020-04-08 19:42:40.613191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888c878214dd'
down_revision = '7cd49552ae02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.String(length=120), nullable=False))
    op.drop_column('show', 'start__time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start__time', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
